services:

  # This compose file relies on a properly configured ".env" file
  # Make a copy of .env.sample to configure your environment

  mysql:
    image: mysql:${MYSQL_VERSION_TAG}
    restart: always
    volumes:
      - "${MYSQL_DATA_VOLUME}:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # -------------------------------------------------------------------------------
    # Uncomment this section to expose mysql to connections outside of the container
    # such as MySQL Workbench
    # -------------------------------------------------------------------------------
mysql

  piwigo:
    image: lscr.io/linuxserver/piwigo:${PIWIGO_VERSION_TAG}
    environment:
      - PUID=${PIWIGO_PUID}
      - PGID=${PIWIGO_GUID}
      - TZ=${PIWIGO_TZ}
    volumes:
      - "${PIWIGO_CONFIG_VOLUME}:/config"
      - "${PIWIGO_GALLERIES_VOLUME}:/gallery/galleries:ro"
    ports:
      - ${PIWIGO_EXTERNAL_PORT}:80
    restart: unless-stopped


